server {
    server_name _;
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        root /www/static/;
    }

    location /rng/ {
        proxy_pass http://rng:8080/;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-Port $remote_port;
    }

    location /upgreat/ {

        location /upgreat/auth/ {
            #if ($scheme = http) {
            #    return 301 https://$host$request_uri;
            #}
            return 403;
        }

        location /upgreat/ {
            proxy_pass http://upgreat-backend:8081/;
            proxy_set_header Host      $host;
        }
    }
}
