FROM alpine:3

RUN ["apk", "add", "npm"]

ENV NODE_ENV=developement
WORKDIR /srv/
COPY . .

WORKDIR client/
RUN ["npm", "clean-install"]
RUN ["npm", "run", "build"]
WORKDIR ../

RUN ["npm", "clean-install"]
RUN ["npm", "run", "build"]

EXPOSE 8081
ENV NODE_ENV=production
ENTRYPOINT ["npm", "run", "start"]
