server {
    server_name         martinjanu.eu www.martinjanu.eu;
    listen              80;
    listen              [::]:80;
    listen              443 ssl;
    listen              [::]:443 ssl;
    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    include /etc/nginx/conf.d/snippets/acme.conf;

    location / {
        root /www/static/;
    }

    location /rng/ {
        proxy_pass http://rng:8080/;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-Port $remote_port;
    }
}
