server {
    server_name		upgreat.martinjanu.eu;
    listen              80;
    listen              [::]:80;
    listen              443 ssl;
    listen              [::]:443 ssl;
    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    include /etc/nginx/conf.d/snippets/acme.conf;

    location /auth/ {
        if ($scheme = http) {
            return 301 https://$host$request_uri;
        }
        return 403;
    }

    location / {
        return 418;  # Coffee maker under construction
    }
}
